modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "walllanterns"
version = "${version}"
displayName = "Lanterns Belong On Walls"
authors = "ThePoultryMan"
description = '''
A mod for Minecraft that allows placing lanterns on walls 
'''
#logoFile = ""

[[dependencies.walllanterns]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walllanterns]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.walllanterns]]
modId = "advanced_runtime_resource_packs_but_different"
type = "required"
versionRange = "[${arrp_but_different_version},)"

[[mixins]]
config = "walllanterns.mixins.json"
